Add controllers
neobelov/java-shareit pull request #1
Opened 2023-02-13 22:08 UTC by neobelov

2023-02-15 07:28 UTC, krylov-sergey-sergeevich requested changes
Привет, ощущение что нужно еще поработать над работой, отметил что надо исправить и ниже еще пару вопросов:

1) Я не увидел Booking - планируется ли оно добавляться?
2) Я не увидел ItemRequest  - планируется ли оно добавляться?
3) Мапперов не увидел
4) Можно поизучать механизм валидации при помощи аннотаций 

Буду ждать с правками и вопросами если есть =)

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    String error;
private final к полям лучше бы добавить

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> getAllWithOwnerCheck(@RequestHeader("X-Sharer-User-Id") Integer owner) {
"X-Sharer-User-Id" эта штука много где повторяется рекомендую ее вынести в класс Constants и использовать переменную

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +public class Item extends ItemDto implements StorageObject<Item> {
**Надо исправить:** Item и ItemDto совершенно различные миры их нельзя связывать, особенно наследованием

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +public class Item extends ItemDto implements StorageObject<Item> {
StorageObject<Item> - тоже сомнительная штука она дает какое удобство?

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item patch(Item item) {
Название метода не очень понятное, выглядит как какое то клонирование

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +public class Item extends ItemDto implements StorageObject<Item> {
Еще есть ощущение что нет переменных
- `available` — статус о том, доступна или нет вещь для аренды;
- `owner` — владелец вещи;
- `request` — если вещь была создана по запросу другого пользователя, то в этом поле будет храниться ссылка на соответствующий запрос.

2023-02-15 07:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User patch(User obj) {
Аналогично сомнительное название

2023-02-15 08:45 UTC, neobelov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public Item patch(Item item) {
Метод убрал, дополнил метод patch в сервисе

2023-02-15 08:45 UTC, neobelov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    public User patch(User obj) {
Метод убрал, дополнил метод patch в сервисе

2023-02-15 08:47 UTC, neobelov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +public class Item extends ItemDto implements StorageObject<Item> {
Наследование убрал, добавил отдельный маппер ItemMapper
переменные наследовались из itemDto, потому здесь их не было, сейчас создал
StorageObject позволяет использовать класс InMemoryStorage и не дублировать код для хранения объектов в памяти

2023-02-15 08:47 UTC, neobelov commented on src/main/java/ru/practicum/shareit/exceptions/ErrorResponse.java
> +    String error;
Сделал

2023-02-15 08:50 UTC, neobelov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public List<ItemDto> getAllWithOwnerCheck(@RequestHeader("X-Sharer-User-Id") Integer owner) {
Сделал

2023-02-16 05:35 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-02-16 05:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/utilities/Constants.java
> +    public static final String sharerUserIdHttpHeader = "X-Sharer-User-Id";
Переменная должна называться SHARER_USER_ID_HTTP_HEADER

2023-02-16 05:58 UTC, neobelov commented on src/main/java/ru/practicum/shareit/utilities/Constants.java
> +    public static final String sharerUserIdHttpHeader = "X-Sharer-User-Id";
Принято

2023-02-16 07:03 UTC, merged